### ISSUE TITLE
Mongo DB read hangs while reading from catalog from Daemon to read and update

### ISSUE THREAD

**Issue by wbari** [opencb/opencga#1076]

**Comment by wbari** [comment]
![image](https://user-images.githubusercontent.com/22955620/51843017-132ef380-230a-11e9-8b02-86ea810aa6e6.png)

**Comment by wbari** [comment]
To rule out azure bacth, I have tried to index the file using LOCAL executor and it hangs with same calls both when start job or later when update the job status in Catalog.

Below is an extract showing IndexDaemon is stuck and only Execution is running. 



	at org.opencb.opencga.storage.core.manager.variant.VariantStorageManager.index(VariantStorageManager.java:172)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.index(VariantCommandExecutor.java:303)
	at org.opencb.opencga.app.cli.analysis.executors.VariantCommandExecutor.execute(VariantCommandExecutor.java:115)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.privateMain(AnalysisMain.java:98)
	at org.opencb.opencga.app.cli.analysis.AnalysisMain.main(AnalysisMain.java:34)
2019-01-29 15:42:40 [index-thread] INFO  IndexDaemon:108 - ----- INDEX DAEMON -----
2019-01-29 15:42:40 [Thread-10] WARN  Configuration:2825 - hbase-site.xml:an attempt to override final parameter: dfs.support.append;  Ignoring.
2019-01-29 15:42:40 [index-thread] INFO  IndexDaemon:182 - Updating job 5027 from RUNNING to ERROR

2019-01-29 15:42:40 [LocalExecutor-0] INFO  LocalExecutor:77 - ==========================================
2019-01-29 15:42:40 [LocalExecutor-0] INFO  LocalExecutor:78 - Finished job variant_index(5027)
2019-01-29 15:42:40 [LocalExecutor-0] INFO  LocalExecutor:79 - ==========================================
2019-01-29 15:42:41 [execution-thread] INFO  ExecutionDaemon:91 - ----- EXECUTION DAEMON -----
2019-01-29 15:42:42 [authorization-thread] INFO  AuthorizationDaemon:50 - ----- AUTHORIZATION DAEMON -----
2019-01-29 15:42:45 [execution-thread] INFO  ExecutionDaemon:91 - ----- EXECUTION DAEMON -----
2019-01-29 15:42:49 [execution-thread] INFO  ExecutionDaemon:91 - ----- EXECUTION DAEMON -----
2019-01-29 15:42:52 [authorization-thread] INFO  AuthorizationDaemon:50 - ----- AUTHORIZATION DAEMON -----
2019-01-29 15:42:53 [execution-thread] INFO  ExecutionDaemon:91 - ----- EXECUTION DAEMON -----

**Comment by wbari** [comment]
These are the commands and parameters to run docker 

PID   USER     TIME  COMMAND
    1 opencga   0:00 /bin/bash -c echo ${OPENCGA_PASS} | /opt/opencga/bin/opencga-admin.sh catalog daemon --start
    7 opencga   0:19 /usr/lib/jvm/java-1.8-openjdk/jre/bin/java -Dlog4j.configuration=file:/opt/opencga/conf/log4j.properties -Xms256m -Xmx8192m -Dfile.encoding=UTF-8 -classpath :/opt/

**Comment by marrobi** [comment]
Just hit this now. Stopped container, started it, complained about job directory already existing, removed the directory and job was queued on batch.

**Comment by pfurio** [comment]
I found these two links that could be somehow related to the issue we have:
- https://stackoverflow.com/questions/13364008/how-to-understand-why-my-mongodb-hangs 
There they basically say the reason could be because the virtual machine where the docker is running is limited to 32 bits. I don't think it will be the case, but worth checking just in case.
- https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8075484 
Here they describe the bug and basically they claim version oracle jdk-8u131 is fixed. Could we try using this java version instead of the openjdk?

**Comment by marrobi** [comment]
These builds are off my laptop - as I have specific docker files (now merged). Building with ➜  
```
mvn -v
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_201, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-17763-microsoft", arch: "amd64", family: "unix"
```
running with images using ```openjdk:8-jre-alpine```

Could be an issue?

**Comment by marrobi** [comment]
The daemon operates as expected when running on the VM rather than in the container. Also tried --network=host .

**Comment by martinpeck** [comment]
related to #1117

**Comment by martinpeck** [comment]
Untagged it from Azure, and from the Azure project.
This is still an issue, but we have a mitigation for this issue now.
The docker containers will restart when unhealthy.
